version: "2"

services:
  client:
    build: ./client/
    restart: always
    ports:
      - "80:80"
    links:
      - api
    hostname: client
    networks:
      - webappnetwork
  api:
    build: ./server/
    restart: always
    ports:
      - "8080:8080"
    hostname: api
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge

