version: "2"

services:
  client:
    build: ./client/
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - api
    networks:
      - webappnetwork
  api:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
      - /api/node_modules
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge

