version: "2"

services:
  client:
    build: ./client/
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - api
    networks:
      - webappnetwork
  api:
    build: ./server/
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api
      - /api/node_modules
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge

