version: "2"

services:
  client:
    image: mhermosi/unit-conversion-client:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - api
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    hostname: client
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - webappnetwork
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  
  api:
    image: mhermosi/unit-conversion-server:latest
    restart: always
    ports:
      - "8080:8080"
    hostname: api
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge

